spring:
  application:
    name: minijournal
    
  datasource:
    url: jdbc:postgresql://localhost:5432/default_database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true # to display SQL queries in the console
    hibernate:
      ddl-auto: none # to let Spring create the schema by running migrations

logging:
    level:
        org:
        springframework:
            web: DEBUG
            
springdoc:
  swagger-ui:
    path: /docs
